name: Deploy Node.js App to Azure

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Deploy to Azure Web App (EastUS1)
        uses: azure/webapps-deploy@v2
        with:
          app-name: EastUS1
          publish-profile: ${{ secrets.secret123 }}
          package: .
