name: Deploy Node.js App to Azure

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to EastUS1 Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: EastUS1
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_EASTUS }}
          package: .   # deploys index.js, file.json, web.config
