name: Deploy Node.js App to Azure

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Optional: Node.js setup skipped because no package.json
      # - name: Setup Node.js
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: 18

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_EASTUS }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: EastUS1
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_EASTUS }}
          package: .
