name: Deploy Node.js App to Azure

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Azure login using publish profile
      - name: Azure Login with Publish Profile
        uses: azure/login@v1
        with:
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_EASTUS }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: EastUS1
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_EASTUS }}
          package: .
